#!/bin/sh
#
# Start the syslog server....
#

DAEMON=syslogd
ARGS="-m 0"

DAEMON_PATH=`which $DAEMON`

start() {
 	echo -n Starting $DAEMON ...
	$DAEMON_PATH $ARGS
	echo running
}	
stop() {
	echo Stopping $DAEMON
	killall $DEAMON
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

