#!/bin/sh
#
# Load the inout driver handling the relais outputs, the buzzer and the digital inputs
#

start() {
    echo -n Loading inout driver ...
	modprobe inout
    echo done
}

stop() {
	echo Unloading inout driver
	modprobe -r inout
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

