#!/bin/sh
#
# Start the ui application....
#

AUTOSTART_FILE=/usr/local/etc/autostart

[ -f $AUTOSTART_FILE ] || exit 1
. $AUTOSTART_FILE

[ _$AUTOSTART_APP != _ ] || exit 1

DAEMON_PATH=`which $AUTOSTART_APP`
PIDFILE=/var/application.pid

export TSLIB_TSDEVICE=/dev/input/event0

start() {
 	echo -n Starting $AUTOSTART_APP ...
    daemonize -p $PIDFILE $DAEMON_PATH $AUTOSTART_ARGS
    echo running
}	
stop() {
	echo Stopping $AUTOSTART_APP
	[ -e $PIDFILE ] && grep $AUTOSTART_APP /proc/`cat $PIDFILE`/cmdline > /dev/null && kill `cat $PIDFILE`
    rm -rf $PIDFILE
}

restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

